version: '3.8'

services:
  movies:
    container_name: django-movies
    image: django-movies:latest
    build: .
    command: python manage.py runserver 0.0.0.0:${PORT}
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
  movies-db:
    container_name: django-movies-postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - 5432:5432
volumes:
  postgres_data: